---
- hosts: webservers
  user: vagrant
  sudo: yes
  gather_facts: no
  vars_files:
    - conf.yml
  roles:
    - core
    - db
    - nginx

- hosts: webservers
  sudo: yes
  user: vagrant
  sudo_user: postgres
  gather_facts: no
  vars_files:
    - conf.yml

  tasks:
  - name: ensure database is created
    action: postgresql_db db={{dbname}}

  - name: ensure user has access to database
    action: postgresql_user db={{dbname}} user={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    action: postgresql_user user={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB