- name: update apt
  action: command /usr/bin/apt-get update
  sudo: true

- name: update cache 
  apt: update_cache=yes
  sudo: true

# Install Python && Django packages

- name: Install dev pkgs
  apt: pkg=$item
  with_items:
    - build-essential
    - python-dev
    - libpq-dev
    - libevent-dev
    - python-pip
    - python-setuptools
    - git
    - curl
    - vim

- name: pip install stuff
  pip: name=$item
  with_items:
    - distribute
    - virtualenv
   
# Install MySQL
 
- name: install mysql
  apt: name=$item state=latest update_cache=yes
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - make

- name: service mysql  
  action: service name=mysql state=started
  
# Install NGINX

- name: install nginx
  action: apt name=nginx